name: Smart Deploy
on: workflow_dispatch
jobs:
    quality_checks:
        runs-on: ubuntu-latest
        if: startsWith(github.ref,'refs/heads/feature') && github.event_name == 'push'
        steps:
            - name: Perform Quality Check
              run: |
                echo "Performing quality check"
                exit 1
    dev_deploy:
        runs-on: ubuntu-latest
        if: github.ref_name == 'develop' && github.event_name == 'push'
        steps:
            - name: Dev Deploy
              run: echo "Deploying to dev environment"
    prod_deploy:
        runs-on: ubuntu-latest
        if: github.ref_name == 'main' && github.event_name == 'push'
        steps:
            - name: Prod Deploy
              run: echo "Deploying to production environment"
    success_notify:
        runs-on: ubuntu-latest
        needs: ['quality_checks','dev_deploy','prod_deploy']
        if: always() && !failure()
        steps:
            - name: Sent Succcess Email
              run: echo "Sending success emai..."
    failure_notify:
        runs-on: ubuntu-latest
        needs: ['quality_checks','dev_deploy','prod_deploy']
        if: failure()
        steps:
            - name: Sent Failure Email
              run: echo "Sending failure emai..."
